name: education_community
description: This Is A Application for Students and teachers community. Where they will update or inform their knowladge


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0

  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_storage: ^4.0.0
  google_sign_in: ^4.5.3
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12
  cloud_firestore: ^0.14.0+2
  uuid: ^2.2.2
  image_picker: ^0.6.7+11
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
     - images/

  fonts:
    - family: electric_1
      fonts:
        - asset: fonts/elec-rg.ttf





